/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lzhz_lxh_sleepmonitor_tools_jni_JNIUtils */

#ifndef _Included_com_lzhz_lxh_sleepmonitor_tools_jni_JNIUtils
#define _Included_com_lzhz_lxh_sleepmonitor_tools_jni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lzhz_lxh_sleepmonitor_tools_jni_JNIUtils
 * Method:    detect0131
 * Signature: (DDDDDD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lzhz_lxh_sleepmonitor_tools_jni_JNIUtils_detect0131
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
